# Generated by Django 5.1.15 on 2026-02-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching_config", "Fetching Config"),
                            ("running_rules", "Running Rules"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("config_snapshot", models.TextField(blank=True)),
                ("config_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("pytest_json_report", models.JSONField(blank=True, null=True)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        help_text="e.g. {passed: 5, failed: 2, error: 0}",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_runs",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cron_expression", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("django_q_schedule_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_node_id", models.CharField(max_length=500)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("severity", models.CharField(default="medium", max_length=10)),
                (
                    "audit_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="audits.auditrun",
                    ),
                ),
                (
                    "custom_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.customrule",
                    ),
                ),
                (
                    "simple_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.simplerule",
                    ),
                ),
            ],
            options={
                "ordering": ["test_node_id"],
            },
        ),
    ]
