# Generated by Django 5.1.15 on 2026-03-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="slack_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Slack incoming webhook URL for audit failure notifications.",
            ),
        ),
    ]
