# Generated by Django 6.0.2 on 2026-02-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="api_endpoint",
            field=models.URLField(blank=True, default=""),
        ),
    ]
