# Generated by Django 6.0.2 on 2026-03-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_api_endpoint"),
        ("devices", "0002_devicegroup_device_groups"),
    ]

    operations = []
