# Generated by Django 5.1.15 on 2026-03-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_sources", "0002_configsource_sshconfigsource"),
        ("devices", "0003_merge_20260301_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="config_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="config_source",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device",
                to="config_sources.configsource",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="last_fetched_config",
            field=models.TextField(blank=True, default=""),
        ),
    ]
