# Generated by Django 5.1.15 on 2026-03-01 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_devicegroup_device_groups"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customrule",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, rule applies to all devices in this group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_rules",
                to="devices.devicegroup",
            ),
        ),
        migrations.AddField(
            model_name="simplerule",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, rule applies to all devices in this group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simple_rules",
                to="devices.devicegroup",
            ),
        ),
    ]
