# Generated by Django 5.1.15 on 2026-03-03 00:14

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("api", "API Endpoint"),
                            ("git", "Git Repository"),
                            ("manual", "Manual"),
                            ("ssh", "SSH (Netmiko)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SshConfigSource",
            fields=[
                (
                    "configsource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="config_sources.configsource",
                    ),
                ),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.IntegerField(default=22)),
                ("username", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "ssh_key",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "command_override",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("prompt_overrides", models.JSONField(blank=True, default=dict)),
                ("timeout", models.IntegerField(default=30)),
                (
                    "netmiko_device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_sources.netmikodevicetype",
                    ),
                ),
            ],
            bases=("config_sources.configsource",),
        ),
    ]
